version: '3'

services:  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - grafana_data:/var/lib/grafana/
    environment:
      - 'GF_SECURITY_ADMIN_USER=danik'
      - 'GF_SECURITY_ADMIN_PASSWORD=qwerty' 

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    hostname: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - '9090:9090'
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"

volumes:
  grafana_data:
