---
# tasks file for java-role
- name: —Åreate app directory
  file:
    path=/var/app/
    state=directory

- name: copy compose file
  copy:
    src: ./files/docker-compose.yaml
    dest: /var/app

- name: Start nginx Docker Compose
  command: docker-compose up -d
  args:
    chdir: /var/app/docker-compose.yaml