---
# tasks file for java-role
- name: —Åreate app directory
  file:
    path: '/var/app/'
    state: directory

- name: copy compose file
  copy:
    src: docker-compose.yaml
    dest: '/var/app/'
    mode: '0777'

- name: copy dockerfile
  copy:
    src: Dockerfile
    dest: '/var/app/'
    mode: '0777'

- name: Start Docker Compose
  docker_compose:
    project_src: '/var/app/'
    state: present
  register: docker_compose_start
