---
# tasks file for monitoring-role
- name: —Åreate monitoring directory
  file:
    path=/var/monitoring/prometheus
    state=directory

- name: copy docker-compose file
  copy:
    src: ./files/docker-compose.yaml
    dest: '/var/monitoring/docker-compose.yaml'
    mode: '0744'

- name: Start monitoring docker Compose
  command: docker-compose up -d
  args:
    chdir: /var/monitoring/docker-compose.yaml

- name: ip facts
  ansible.builtin.set_fact:
    target_ip: "{{ hostvars['prod1']['ansible_host'] }}"

- name: monitor
  debug:
    msg: "{{ target_ip }}"

- name: copy docker-compose file
  template:
    src: prometheus.yaml.j2 
    dest: '/var/monitoring/prometheus/prometheus.yaml'
    mode: '0744'

- name: Replace Server with {{ ansible_host }}
  replace:
    path: "/var/monitoring/prometheus/prometheus.yaml"
    regexp: 'targets: \[\:8080\]'
    replace: 'targets: [{{ target_ip }}:8080]'

- name: Replace Server with {{ ansible_host }}
  replace:
    path: "/var/monitoring/prometheus/prometheus.yaml"
    regexp: 'targets: \[\:9100\]'
    replace: 'targets: [{{ target_ip }}:9100]'
