---
# tasks file for monitoring-role
- name: —Åreate monitoring directory
  file:
    path: /var/monitoring/prometheus
    state: directory

- name: copy docker-compose file
  copy:
    src: docker-compose.yaml
    dest: '/var/monitoring/docker-compose.yaml'
    mode: '0777'

- name: Start Docker Compose
  docker_compose:
    project_src: '/var/monitoring/'
    state: present

- name: copy prometheus file
  template:
    src: prometheus.yml.j2 
    dest: '/var/monitoring/prometheus/prometheus.yml'
    mode: '0744'

- name: ip facts
  ansible.builtin.set_fact:
    target_ip: "{{ hostvars['prod1']['ansible_host'] }}"

- name: monitor
  debug:
    msg: "{{ target_ip }}"

- name: Replace Server with {{ ansible_host }}
  replace:
    path: "/var/monitoring/prometheus/prometheus.yml"
    regexp: 'targets: \[\:8080\]'
    replace: 'targets: [{{ target_ip }}:8080]'

- name: Replace Server with {{ ansible_host }}
  replace:
    path: "/var/monitoring/prometheus/prometheus.yml"
    regexp: 'targets: \[\:9100\]'
    replace: 'targets: [{{ target_ip }}:9100]'
