---
# defaults file for install-docker-role
all_packages:
  - curl
  - wget
  - vim
  - net-tools
  - mc
  - htop
  - apt-transport-https 
  - ca-certificates 
  - python3-setuptools
  - python3-pip
  - software-properties-common
  - virtualenv
  - expect

docker_url: https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-aarch64

gpg_docker_url: https://download.docker.com/linux/ubuntu/gpg